const Map<String, List<String>> categories = {
  "Football_teams": [
    "Barcelona",
    "Real Madrid",
    "Manchester United",
    "Bayern Munich",
    "Chelsea",
    "Liverpool",
    "Juventus",
    "Paris Saint-Germain",
    "Arsenal",
    "Manchester City",
    "Tottenham Hotspur",
    "AC Milan",
    "Inter Milan",
    "Borussia Dortmund",
    "Atletico Madrid",
    "Napoli",
    "Roma",
    "Ajax",
    "Benfica",
    "Porto"
  ],
  "Football_players": [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Neymar",
    "Kylian Mbappe",
    "Robert Lewandowski",
    "Kevin De Bruyne",
    "Mohamed Salah",
    "Virgil van Dijk",
    "Sergio Ramos",
    "Harry Kane",
    "Eden Hazard",
    "Paulo Dybala",
    "Luka Modric",
    "Sadio Mane",
    "Paul Pogba",
    "Antoine Griezmann",
    "Erling Haaland",
    "Gareth Bale",
    "Raheem Sterling",
    "Zlatan Ibrahimovic"
  ],
  "Baseball": [
    "Pitcher",
    "Catcher",
    "Home run",
    "Strikeout",
    "Double play",
    "Stolen base",
    "Grand slam",
    "No-hitter",
    "Batting average",
    "ERA (Earned Run Average)",
    "Outfielder",
    "Infield",
    "Shortstop",
    "Slugger",
    "Curveball",
    "Fastball",
    "Changeup",
    "Bullpen",
    "Home plate",
    "Mound"
  ],
  "Hockey": [
    "Puck",
    "Slapshot",
    "Hat trick",
    "Power play",
    "Penalty kill",
    "Faceoff",
    "Goaltender",
    "Blue line",
    "Offside",
    "Icing",
    "Breakaway",
    "Checking",
    "Wrist shot",
    "Overtime",
    "Shootout",
    "Penalty box",
    "Assist",
    "Backhand",
    "Forecheck",
    "Deke"
  ],
  "Cricket": [
    "Wicket",
    "Batsman",
    "Bowler",
    "All-rounder",
    "Century",
    "Duck",
    "Run-out",
    "Stumping",
    "Over",
    "Boundary",
    "Six",
    "Four",
    "Innings",
    "LBW (Leg Before Wicket)",
    "No-ball",
    "Wide",
    "Spin bowler",
    "Pace bowler",
    "Slip",
    "Gully"
  ],
  "Basketball_players": [
    "Michael Jordan",
    "LeBron James",
    "Kobe Bryant",
    "Magic Johnson",
    "Larry Bird",
    "Shaquille O'Neal",
    "Tim Duncan",
    "Kevin Durant",
    "Stephen Curry",
    "Wilt Chamberlain",
    "Bill Russell",
    "Kareem Abdul-Jabbar",
    "Hakeem Olajuwon",
    "Charles Barkley",
    "Dirk Nowitzki",
    "Scottie Pippen",
    "Dwyane Wade",
    "Karl Malone",
    "Chris Paul",
    "Giannis Antetokounmpo"
  ],
  "Basketball_history": [
    "Naismith",
    "NBA",
    "ABA",
    "March Madness",
    "Dream Team",
    "Harlem Globetrotters",
    "Wilt 100",
    "Magic vs Bird",
    "Bulls dynasty",
    "Showtime Lakers",
    "Celtics dynasty",
    "Mikan",
    "3-point line",
    "Shot clock",
    "All-Star Game",
    "MVP",
    "Rookie of the Year",
    "Finals",
    "Hall of Fame",
    "Olympic gold"
  ],
  "Football_history": [
    "World Cup",
    "Pele",
    "Maradona",
    "Hand of God",
    "Total Football",
    "Busby Babes",
    "The Invincibles",
    "Galacticos",
    "Tiki-taka",
    "Johan Cruyff",
    "Franz Beckenbauer",
    "Champions League",
    "Treble",
    "Golden Boot",
    "FIFA",
    "UEFA",
    "Copa America",
    "Ballon d'Or",
    "Serie A",
    "La Liga"
  ],
  "Sport_MIX": [
    "Olympics",
    "Paralympics",
    "World Cup",
    "Super Bowl",
    "Wimbledon",
    "Tour de France",
    "Masters",
    "Formula 1",
    "UFC",
    "Ryder Cup",
    "Grand Slam",
    "Ironman",
    "X Games",
    "Commonwealth Games",
    "Stanley Cup",
    "Heisman Trophy",
    "NCAA",
    "Six Nations",
    "MotoGP",
    "America's Cup"
  ],
  "General_words": [
    "Athlete",
    "Coach",
    "Referee",
    "Medal",
    "Victory",
    "Defeat",
    "Competition",
    "Training",
    "Team",
    "League",
    "Season",
    "Match",
    "Tournament",
    "Record",
    "Stadium",
    "Spectator",
    "Sportsmanship",
    "Fitness",
    "Injury",
    "Goal"
  ]
};
